version: '2'
services:
    bestmeal-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/BestMeal/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=BestMeal
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
